routes/web.php
<?php
Auth::routes();

Route::group(['middleware' => ['web', 'auth']], function () {
    Route::get('/', function () {return redirect(route('app.index'));});

    Route::resource('user', 'User\UsersController')->middleware('roles:admin');
    Route::resource('Area', 'AreaController')->middleware('roles:write,admin');
    Route::resource('app', 'ApplicantController');

    Route::get('app/{id}/print', 'ApplicantController@print')->name('app.print');
    Route::get('app/{id}/printer', function ($id) {
        $header    = view('applicant.backup.header')->render();
        $applicant = App\Applicants\applicant::with('inArea', 'experiences')->find($id);
        $backup    = new App\Http\Controllers\backup\backup();
        $data      = $backup->GetData($applicant);
        $view      = view('applicant.backup.printer')->with($data)->render();
        $footer    = '</body></html>';
        return $header . $view . $footer;
    })->name('app.printer');
    Route::get('app/{id}/printer2', function ($id) {
        $applicant = App\Applicants\applicant::with('inArea', 'experiences')->find($id);
        $backup    = new App\Http\Controllers\backup\backup();
        $data      = $backup->GetData($applicant);
        return view('applicant.backup.printer2')->with($data)->render();
    })->name('app.printer2');
    Route::get('app/{id}/download', 'backup\backup@download')->name('app.download')->middleware('roles:backup,admin');
    Route::post('backup', 'backup\backup@backupProcess')->middleware('roles:backup,admin');
    Route::get('home', 'ApplicantController@index')->name('home');
    Route::get('check', 'ApplicantController@check')->name('check');
    Route::get('search', 'SearchController@filter')->name('search');
    Route::get('backup', 'ApplicantController@backupView')->name('app.backup')->middleware('roles:backup,admin');
});
Route::get('migrate', function () {
    Artisan::call('migrate');
});

app/User.php
<?php

namespace App;

use App\Role;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    public $timestamps = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /* Relation */
    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function authorizeRoles($roles)
    {
        if (is_array($roles)) {
            if ($this->hasAnyRole($roles) == true) {
                return true;
            } else {
                return abort(401, 'This action is unauthorized.');
            }
        }
        if ($this->hasRole($roles) == true) {
            return true;
        } else {
            return abort(401, 'This action is unauthorized.');
        }
    }
    /**
     * Check multiple roles
     * @param array $roles
     */
    public function hasAnyRole($roles)
    {
        return null !== $this->roles()->whereIn('name', $roles)->first();
    }
    /**
     * Check one role
     * @param string $role
     */
    public function hasRole($role)
    {
        return null !== $this->roles()->where('name', $role)->first();
    }

}

app/Http/Controllers/User/UsersController.php
<?php
namespace App\Http\Controllers\User;

use App\DataTables\UserDataTable;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user  = new UserDataTable();
        $users = user::select('id', 'name', 'email');
        return $user->with(['data' => $users])->render('users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'name'     => 'required|string|max:255',
            'email'    => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);

        $user = User::create([
            'name'     => $request['name'],
            'email'    => $request['email'],
            'password' => bcrypt($request['password']),
        ]);
        if (!empty($request['Roule'])) {
            $user->roles()->sync($request['Roule']);
        }

        Session::flash('flash_message', 'تم اضافة المستخدم بنجاح');

        return redirect(route('user.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::with("roles")->findOrFail($id);
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request

     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $value = $this->validate($request, [
            'id'       => 'required|integer|max:255',
            'name'     => 'required|string|max:255',
            'email'    => 'required|email|max:255|unique:users,email,' . $id,
            'password' => 'nullable|string|min:6|confirmed',
        ]);
        if ($value['password'] == null) {
            unset($value['password']);
        } else {
            $value['password'] = bcrypt($request['password']);
        }
        User::where('id', $value['id'])->update($value);

        $user = User::find($value['id']);
        if (!empty($request['Roule'])) {
            $user->roles()->sync($request['Roule']);
        } else {
            $user->roles()->detach();
        }

        Session::flash('flash_message', 'تم تعديل بيانات المستخدم بنجاح');

        return redirect(route('user.index'));
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $User = User::findOrFail($id);
        $User->delete();

        return "";
    }
}

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('title','Edit User')
@section('jsSection')
<script type="text/javascript">
    $(function(){
        $(".admin").click(function(){
            $('#Roule input:checkbox').not(this).prop('checked', this.checked);
        });
    });
</script>
@endsection
@section('content')
<div class="col-sm-11">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">تعديل مستخدم </h3>
        </div>
        @include('layouts.message')
        <form class="form-horizontal" method="POST" action="{{ route('user.update',$user->id) }}">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
            <input type="hidden" name="id" value="{{ $user->id }}">
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name" class="col-md-4 control-label">الاسم</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name',$user->name) }}" required autofocus>

                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                <label for="email" class="col-md-4 control-label">البريد الالكترونى</label>

                <div class="col-md-6">
                    <input id="email" type="email" class="form-control" name="email" value="{{ old('email',$user->email) }}" required>

                    @if ($errors->has('email'))
                        <span class="help-block">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                <label for="password" class="col-md-4 control-label">كلمة المرور</label>

                <div class="col-md-6">
                    <input id="password" type="password" value="" class="form-control" name="password" >

                    @if ($errors->has('password'))
                        <span class="help-block">
                            <strong>{{ $errors->first('password') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <label for="password-confirm" class="col-md-4 control-label">تاكيد كلمة المرور</label>

                <div class="col-md-6">
                    <input id="password-confirm" type="password" class="form-control" value="" name="password_confirmation" >
                </div>
            </div>
            <div class="form-group">
                <label for="Roule" class="col-md-4 control-label">الصلحيات</label>

                <div class="col-md-6" id="Roule">
                    <label class="checkbox-inline">
                      <input type="checkbox" name="Roule[]" {{$user->hasRole('write') ? 'checked' : '' }} value="1">Write / Edit
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" name="Roule[]" {{$user->hasRole('delete') ? 'checked' : '' }} value="2">Delete
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" name="Roule[]" {{$user->hasRole('backup') ? 'checked' : '' }} value="3">Backup
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" class="admin" {{$user->hasRole('admin') ? 'checked' : '' }} name="Roule[]" value="4">Admin
                    </label>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                        حفظ
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')
@section('title','Add Application')
@section('addApplication','class="active"')
@section('cssSection')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('plugins/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.0.3/css/buttons.dataTables.min.css">
<meta name="csrf-token" content="{{csrf_token()}}">
@endsection

@section('jsSection')
<!-- DataTables -->
<script src="{{asset('plugins/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('plugins/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('vendor/datatables/buttons.server-side.js')}}"></script>
<script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
<!-- page script -->
<script type="text/javascript">
    $('#dataTableBuilder').on('click', '.btn-delete[data-remote]', function (e) {
    e.preventDefault();
     $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    var url = $(this).data('remote');
    // confirm then
    if (confirm('هل انت اتاكد من حذف هذا المستخدم؟')) {
        $.ajax({
            url: url,
            type: 'DELETE',
            dataType: 'json',
            data: {method: '_DELETE', submit: true}
        }).always(function (data) {
            $('#dataTableBuilder').DataTable().draw(false);
            alert('تم حذف المستخدم بنجاح');
        });
    }else
        alert("تم الغاء الامر");
});
</script>
{!! $dataTable->scripts() !!}
@endsection

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">عرض الاعضاء المسجلين</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
            @include('layouts.message')
            {!! $dataTable->table() !!}
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

resources/views/users/register.blade.php
@extends('layouts.app')
@section('title','Add New User')
@section('content')
<div class="col-sm-11">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">اﻧﺸﺎء مستخدم جديد</h3>
        </div>
        @include('layouts.message')
        <form class="form-horizontal" method="POST" action="{{ route('user.store') }}">
            {{ csrf_field() }}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name" class="col-md-4 control-label">الاسم</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                <label for="email" class="col-md-4 control-label">البريد الالكترونى</label>

                <div class="col-md-6">
                    <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                    @if ($errors->has('email'))
                        <span class="help-block">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                <label for="password" class="col-md-4 control-label">كلمة المرور</label>

                <div class="col-md-6">
                    <input id="password" type="password" class="form-control" name="password" required>

                    @if ($errors->has('password'))
                        <span class="help-block">
                            <strong>{{ $errors->first('password') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <label for="password-confirm" class="col-md-4 control-label">تاكيد كلمة المرور</label>

                <div class="col-md-6">
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                </div>
            </div>
            <div class="form-group">
                <label for="Roule" class="col-md-4 control-label">الصلحيات</label>

                <div class="col-md-6" id="Roule">
                    <label class="checkbox-inline">
                      <input type="checkbox" name="Roule[]" value="1">Write / Edit
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" name="Roule[]" value="2">Delete
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" name="Roule[]" value="3">Backup
                    </label>
                    <label class="checkbox-inline">
                      <input type="checkbox" class="admin" name="Roule[]" value="4">Admin
                    </label>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                        حفظ
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection