routes/web.php
<?php
Auth::routes();

Route::group(['middleware' => ['web', 'auth']], function () {
    Route::get('/', function () {return redirect(route('app.index'));});

    Route::resource('user', 'User\UsersController')->middleware('roles:admin');
    Route::resource('Area', 'AreaController')->middleware('roles:write,admin');
    Route::resource('app', 'ApplicantController');

    Route::get('app/{id}/print', 'ApplicantController@print')->name('app.print');
    Route::get('app/{id}/printer', function ($id) {
        $header    = view('applicant.backup.header')->render();
        $applicant = App\Applicants\applicant::with('inArea', 'experiences')->find($id);
        $backup    = new App\Http\Controllers\backup\backup();
        $data      = $backup->GetData($applicant);
        $view      = view('applicant.backup.printer')->with($data)->render();
        $footer    = '</body></html>';
        return $header . $view . $footer;
    })->name('app.printer');
    Route::get('app/{id}/printer2', function ($id) {
        $applicant = App\Applicants\applicant::with('inArea', 'experiences')->find($id);
        $backup    = new App\Http\Controllers\backup\backup();
        $data      = $backup->GetData($applicant);
        return view('applicant.backup.printer2')->with($data)->render();
    })->name('app.printer2');
    Route::get('app/{id}/download', 'backup\backup@download')->name('app.download')->middleware('roles:backup,admin');
    Route::post('backup', 'backup\backup@backupProcess')->middleware('roles:backup,admin');
    Route::get('home', 'ApplicantController@index')->name('home');
    Route::get('check', 'ApplicantController@check')->name('check');
    Route::get('search', 'SearchController@filter')->name('search');
    Route::get('backup', 'ApplicantController@backupView')->name('app.backup')->middleware('roles:backup,admin');
});
Route::get('migrate', function () {
    Artisan::call('migrate');
});

app/Http/Controllers/AreaController.php
<?php

namespace App\Http\Controllers;

use App\Applicants\Area;
use App\Applicants\branch;
use App\DataTables\AreaDataTable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class AreaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Area  = new AreaDataTable();
        $Areas = Area::select('name', 'area_id');
        return $Area->with(['data' => $Areas])->render('Area.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $branchs = branch::all();
        return view('Area.create', compact('branchs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
        ]);
        $Area = Area::create([
            'name' => $request->name,
        ]);
        $Area->selection()->sync($request['branch']);

        Session::flash('flash_message', 'تم اضافة المنطقة بنجاح');

        return redirect(route('Area.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }
    public function branchIN($branchs, $selections)
    {
        foreach ($branchs as $keyb => $branch) {
            if (count($selections) >= 1) {
                foreach ($selections as $keys => $selection) {
                    if ($selection->id === $branch->id) {
                        $branchIN[$keyb]['name'] = $branch->name;
                        $branchIN[$keyb]['id']   = $branch->id;
                        $branchIN[$keyb]['avas'] = "1";
                        break;
                    } else {
                        $branchIN[$keyb]['name'] = $branch->name;
                        $branchIN[$keyb]['id']   = $branch->id;
                        $branchIN[$keyb]['avas'] = "0";
                    }
                }
            } else {
                $branchIN[$keyb]['name'] = $branch->name;
                $branchIN[$keyb]['id']   = $branch->id;
                $branchIN[$keyb]['avas'] = "0";}
        }
        return $branchIN;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Area    = Area::where('area_id', $id)->with('selection')->first();
        $branch  = branch::all();
        $branchs = $this->branchIN($branch, $Area->selection);
        return view('Area.edit', compact('Area', 'branchs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request

     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $value = $this->validate($request, [
            'area_id' => 'required|integer|max:255',
            'name'    => 'required|string|max:255',
        ]);
        Area::where('area_id', $value['area_id'])->update($value);

        $area = Area::where('area_id', $value['area_id'])->first();
        if (!empty($request['branch'])) {
            $area->selection()->sync($request['branch']);
        } else {
            $area->selection()->detach();
        }

        Session::flash('flash_message', 'تم تعديل بيانات المستخدم بنجاح');

        return redirect(route('Area.index'));
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return "";
    }
}

resources/views/Area/create.blade.php
@extends('layouts.app')
@section('title','Edit Area')
@section('jsSection')
@endsection
@section('content')
<div class="col-sm-11">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">اضافة منطقة</h3>
        </div>
        @include('layouts.message')
        <form class="form-horizontal" method="POST" action="{{ route('Area.store') }}">
            {{ csrf_field() }}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name" class="col-md-4 control-label">الاسم</label>
                <div class="col-md-6">
                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <div class="form-group">
                <label for="Roule" class="col-md-4 control-label">الفروع</label>
                <div class="col-md-6" id="Roule">
                @foreach ($branchs as $branch)
                    <label class="checkbox-inline">
                      <input type="checkbox" name="branch[]" value="{{$branch->id}}">{{$branch->name}}
                    </label>
                @endforeach
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                        حفظ
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/Area/edit.blade.php
@extends('layouts.app')
@section('title','Edit Area')
@section('jsSection')
@endsection
@section('content')
<div class="col-sm-11">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">تعديل منطقة</h3>
        </div>
        @include('layouts.message')
        <form class="form-horizontal" method="POST" action="{{ route('Area.update',$Area->area_id) }}">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
            <input type="hidden" name="area_id" value="{{ $Area->area_id }}">
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name" class="col-md-4 control-label">الاسم</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name',$Area->name) }}" required autofocus>

                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <div class="form-group">
                <label for="Roule" class="col-md-4 control-label">الفروع</label>

                <div class="col-md-6" id="Roule">
                    @foreach ($branchs as $name => $branch)
                        <label class="checkbox-inline">
                          <input type="checkbox" name="branch[]" <?php if ($branch['avas'] === "1") {echo 'checked="checked"';}?> value="{{$branch['id']}}">{{$branch['name']}}
                        </label>
                    @endforeach
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                        حفظ
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/Area/index.blade.php
@extends('layouts.app')
@section('title','Show Area')
@section('cssSection')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('plugins/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.0.3/css/buttons.dataTables.min.css">
<meta name="csrf-token" content="{{csrf_token()}}">
@endsection
@section('jsSection')
<!-- DataTables -->
<script src="{{asset('plugins/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('plugins/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('vendor/datatables/buttons.server-side.js')}}"></script>
<script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
<!-- page script -->
<script type="text/javascript">
    $('#dataTableBuilder').on('click', '.btn-delete[data-remote]', function (e) {
    e.preventDefault();
     $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    var url = $(this).data('remote');
    // confirm then
    if (confirm('هل انت متاكد من حذف هذه المنطقة')) {
        $.ajax({
            url: url,
            type: 'DELETE',
            dataType: 'json',
            data: {method: '_DELETE', submit: true}
        }).always(function (data) {
            $('#dataTableBuilder').DataTable().draw(false);
            alert('تم حذف المنطقة بنجاح');
        });
    }else
        alert("لقد تم الغاء الامر");
});
</script>
{!! $dataTable->scripts() !!}
@endsection

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">عرض المناطق</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
            @include('layouts.message')
            {!! $dataTable->table() !!}
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection